version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672       # For applications
      - 15672:15672     # For management UI
    volumes:
      - ~/apps/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

